[[block]]
filters = 344
repeat = 1
kernel = [ 9,]
stride = [ 3,]
dilation = [ 1,]
dropout = 0.05
residual = false
separable = false

[[block]]
filters = 424
repeat = 2
kernel = [ 115,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.05
residual = true
separable = true

[[block]]
filters = 464
repeat = 7
kernel = [ 5,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.05
residual = true
separable = true

[[block]]
filters = 456
repeat = 4
kernel = [ 123,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.05
residual = true
separable = true

[[block]]
filters = 440
repeat = 9
kernel = [ 9,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.05
residual = true
separable = true

[[block]]
filters = 280
repeat = 6
kernel = [ 31,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.05
residual = true
separable = true

[[block]]
filters = 384
repeat = 1
kernel = [ 67,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.05
residual = false
separable = true

[[block]]
filters = 48
repeat = 1
kernel = [ 15,]
stride = [ 1,]
dilation = [ 1,]
dropout = 0.05
residual = false
separable = false

[model]
package = "bonito.ctc"


[labels]
labels = [ "N", "A", "C", "G", "T",]

[input]
features = 1

[encoder]
activation = "relu"

